apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-cd-app-pvc
  labels:
    app: ci-cd-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2 